name: release
on:
  workflow_call:
    inputs:
      upload-type:
        required: true
        type: string
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yaml
  upload-artefact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artefact
        uses: actions/download-artifact@v8
        with:
          name: installer-build
          path: releases/.
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y sshpass
      - name: Push to Hetzner
        env:
          PKG_VER: "installer-${{ needs.build.outputs.installer_ver }}"
          SSHPASS: ${{ secrets.PASSWORD }}
          UPLOAD_TYPE: ${{ inputs.upload-type }}
        run: |
          if [ ! -e "releases/${PKG_VER}" ]; then
              echo "Package not found!"
              exit 1
          fi

          upload() {
              sshpass -e scp -o StrictHostKeyChecking=no "${1}" asahim@asahi-alarm.org:"/public_html/${1}.tmp"
              sshpass -e sftp -o StrictHostKeyChecking=no -o BatchMode=no -b - asahim@asahi-alarm.org << EOF
          rename /public_html/${1}.tmp /public_html/${1}
          EOF
          }

          cd releases
          upload "${PKG_VER}"

          if [ "${UPLOAD_TYPE}" = "installer" ]; then
              upload "latest"
          fi
